#include "Game1.h"

#pragma region Entity Psuedo-Virtuals
enum class UPDATE // Update
{
	ENTITY,
	FADEOUT, COLLECTIBLE, EXPLODENEXTFRAME, UPEXPLODENEXTFRAME, FADEOUTPUDDLE, VACUUMFOR,
	PROJECTILE,
	FUNCTIONALBLOCK, FUNCTIONALBLOCK2,
	VINE,
	BASIC_TURRET, CIRCLE_TURRET, LASER_TURRET,
	ENEMY, VACUUMER, SPIDER, CENTICRAWLER, POUNCER, CAT, CATACLYSM,
	EGG, KIWI,
	PLAYER, FLARE,
	GRENADE, FLAME_GLOB, FLAME_PUDDLE, ENG_TURRET,
	BASE
};

vector<function<void(Entity*)>> updates;

enum class VUPDATE // Velocity Update
{
	ENTITY, AIR_RESISTANCE, GRAVITY, GRAVITY_TRUE, FRICTION, PROJECTILE, VINE, SNAKE, SNAKECONNECTED, SPIDER, CENTICRAWLER, THIEF
};

vector<function<void(Entity*)>> vUpdates;

enum class DUPDATE // Draw Update
{
	ENTITY,
	FADEOUT, COLLECTIBLE, FADEOUTPUDDLE, FADEOUTGLOW,
	PROJECTILE,
	DTOCOL,
	SHRUB, TREE,
	BASIC_TURRET, CIRCLE_TURRET, LASER_TURRET,
	DECEIVER, PARENT, EXPLODER, SNAKECONNECTED, COLORCYCLER, POUNCER, CAT, CATACLYSM, TANK, LASER_TANK,
	KIWI,
	PLAYER,
	ENG_TURRET,
	TURRET, ROVER
};

vector<function<void(Entity*)>> dUpdates;

enum class UIUPDATE // User-Interface Update
{
	ENTITY, SHRUB, TREE, VINE, ENEMY, SNAKECONNECTED, PLAYER, FLARE, ENGINEER
};

vector<function<void(Entity*)>> uiUpdates;

enum class ONDEATH
{
	ENTITY, FADEOUTGLOW, SHOTITEM, LIGHTBLOCK, LIGHTTOWER, ENEMY, PARENT, EXPLODER, SNAKE, POUNCERSNAKE, SNAKECONNECTED, VACUUMER, SPIDER,
	CENTICRAWLER, THIEF, KIWI, PLAYER, BASE
};

vector<function<void(Entity*, Entity*)>> onDeaths;
#pragma endregion